# Dockerfile.handler

FROM python:3.10-slim

# Install ffmpeg for Whisper to work
RUN apt-get update \
 && apt-get install -y --no-install-recommends ffmpeg \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /handler

# Install Python dependencies
COPY handler/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy in the handler code
COPY handler/handler.py ./

# Run the handler
CMD ["python", "handler.py"]
